
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  nextjs:
    build:
      context: .
      dockerfile: nextjs/Dockerfile.dev # 専用Dockerfileを指定
    env_file: .env
    volumes:
      - ./nextjs:/app        # ホストの編集をコンテナに同期
      - /app/node_modules    # コンテナのライブラリを優先
      - /app/.next     
      - ./packages/shogi-logic:/app/node_modules/@torassen/shogi-logic      # キャッシュを隔離
    command: >
      sh -c "cd /app/node_modules/@torassen/shogi-logic && npx tsc -w & cd /app && npm run dev"
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy

  ws-server:
    build:
      context: .
      dockerfile: ws-server/Dockerfile
    restart: unless-stopped
    env_file: .env
    depends_on:
      - nextjs
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:443"
    depends_on:
      - nextjs
      - ws-server

volumes:
  postgres-data:
