FROM nginx:alpine

# Install certbot for Let's Encrypt
RUN apk add --no-cache certbot certbot-nginx openssl

# Copy configurations
COPY nginx.aws.conf /etc/nginx/conf.d/default.conf
COPY entrypoint-aws.sh /docker-entrypoint.d/10-ssl-setup.sh
RUN chmod +x /docker-entrypoint.d/10-ssl-setup.sh

EXPOSE 80 443
